spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    druid:
      #配置数据源监控
      filter:
        stat:
          enabled: true
          logSlowSql: true
          slowSqlMillis: 500
        wall:
          enabled: true
        log4j2:
          enabled: true
      aopPatterns: com.doart.*.dao.*
      ##### WebStatFilter配置 #######
      #启用StatFilter
      webStatFilter:
        enabled: true
        #添加过滤规则
        urlPattern: /*
        #排除一些不必要的url
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
        #开启session统计功能
        sessionStatEnable: true
        #缺省sessionStatMaxCount是1000个
        sessionStatMaxCount: 1000
      ##### StatViewServlet配置 #######
      #启用内置的监控页面
      statViewServlet:
        enabled: true
        #内置监控页面的地址
        urlPattern: /druid/*
        #关闭 Reset All 功能
        resetEnable: false
        #设置登录用户名
        loginUsername: admin
        #设置登录密码
        loginPassword: admin
        #白名单（如果allow没有配置或者为空，则允许所有访问）
        allow: 127.0.0.1,192.168.0.112
        #黑名单（deny优先于allow，如果在deny列表中，就算在allow列表中，也会被拒绝）
        deny:
      cj:
        #数据库连接
        url: jdbc:mysql://192.168.1.104:3306/gf_cj?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=CONVERT_TO_NULL
        #数据库用户名密码
        username: root
        password: shang1234
        #初始化连接池大小
        initialSize: 1
        #最大空闲值.当经过一个高峰时间后，连接池可以慢慢将已经用不到的连接慢慢释放一部分，一直减少到maxIdle为止
        minIdle: 1
        #最大活跃数
        maxActive: 20
        #最大建立连接等待时间。如果超过此时间将接到异常。设为－1表示无限制
        maxWait: 60000
        #失效检查线程运行时间间隔，要小于MySQL默认
        timeBetweenEvictionRunsMillis: 60000
        #连接的超时时间，默认为半小时
        minEvictableIdleTimeMillis: 300000
        #检查连接有效性的SQL语句
        validationQuery: SELECT now()
        #检查连接是否有效
        testWhileIdle: true
        testOnBorrow: true
        testOnReturn: false
        #开启池的prepared statement 池功能
        poolPreparedStatements: false
        #statement池能够同时分配的打开的statements的最大数量
        maxOpenPreparedStatements: 50
      uls:
        #数据库连接
        url: jdbc:mysql://192.168.1.105:3306/gf_uls?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=CONVERT_TO_NULL
        #数据库用户名密码
        username: root
        password: shang1234
        #初始化连接池大小
        initialSize: 1
        #最大空闲值.当经过一个高峰时间后，连接池可以慢慢将已经用不到的连接慢慢释放一部分，一直减少到maxIdle为止
        minIdle: 1
        #最大活跃数
        maxActive: 20
        #最大建立连接等待时间。如果超过此时间将接到异常。设为－1表示无限制
        maxWait: 60000
        #失效检查线程运行时间间隔，要小于MySQL默认
        timeBetweenEvictionRunsMillis: 60000
        #连接的超时时间，默认为半小时
        minEvictableIdleTimeMillis: 300000
        #检查连接有效性的SQL语句
        validationQuery: SELECT now()
        #检查连接是否有效
        testWhileIdle: true
        testOnBorrow: true
        testOnReturn: false
        #开启池的prepared statement 池功能
        poolPreparedStatements: true
        #statement池能够同时分配的打开的statements的最大数量
        maxOpenPreparedStatements: 50