spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    druid:
      cj:
        #数据库连接
        url: jdbc:mysql://192.168.1.104:3306/gf_cj?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=CONVERT_TO_NULL
        #数据库用户名密码
        username: root
        password: shang1234
        #初始化连接池大小
        initialSize: 1
        #最大空闲值.当经过一个高峰时间后，连接池可以慢慢将已经用不到的连接慢慢释放一部分，一直减少到maxIdle为止
        minIdle: 1
        #最大活跃数
        maxActive: 20
        #最大建立连接等待时间。如果超过此时间将接到异常。设为－1表示无限制
        maxWait: 60000
        #失效检查线程运行时间间隔，要小于MySQL默认
        timeBetweenEvictionRunsMillis: 60000
        #连接的超时时间，默认为半小时
        minEvictableIdleTimeMillis: 300000
        #检查连接有效性的SQL语句
        validationQuery: SELECT now()
        #检查连接是否有效
        testWhileIdle: true
        testOnBorrow: true
        testOnReturn: false
        #开启池的prepared statement 池功能
        poolPreparedStatements: false
        #statement池能够同时分配的打开的statements的最大数量
        maxOpenPreparedStatements: 50
      uls:
        #数据库连接
        url: jdbc:mysql://192.168.1.105:3306/gf_uls?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=CONVERT_TO_NULL
        #数据库用户名密码
        username: root
        password: shang1234
        #初始化连接池大小
        initialSize: 1
        #最大空闲值.当经过一个高峰时间后，连接池可以慢慢将已经用不到的连接慢慢释放一部分，一直减少到maxIdle为止
        minIdle: 1
        #最大活跃数
        maxActive: 20
        #最大建立连接等待时间。如果超过此时间将接到异常。设为－1表示无限制
        maxWait: 60000
        #失效检查线程运行时间间隔，要小于MySQL默认
        timeBetweenEvictionRunsMillis: 60000
        #连接的超时时间，默认为半小时
        minEvictableIdleTimeMillis: 300000
        #检查连接有效性的SQL语句
        validationQuery: SELECT now()
        #检查连接是否有效
        testWhileIdle: true
        testOnBorrow: true
        testOnReturn: false
        #开启池的prepared statement 池功能
        poolPreparedStatements: false
        #statement池能够同时分配的打开的statements的最大数量
        maxOpenPreparedStatements: 50